# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
target 'LiveDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'AFNetworking', '~> 3.2.1'
  
  
  # Xcode9.0 iOS 11
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
  
  pod 'Firebase/Core'

  pod 'GoogleSignIn'

  pod 'FBSDKCoreKit',  '~> 4.34.0'
  pod 'FBSDKLoginKit',  '~> 4.34.0'
  pod 'FBSDKShareKit',  '~> 4.34.0'

  # Pods for LiveDemo

  target 'LiveDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
